"""Add orders and kyc tables

Revision ID: c33a585852d6
Revises: 522464856c40
Create Date: 2025-11-25 07:47:31.641360+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'c33a585852d6'
down_revision: Union[str, None] = '522464856c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'signal_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Related trading signal (if applicable)',
               existing_nullable=True)
    op.alter_column('notifications', 'notification_type',
               existing_type=postgresql.ENUM('EMAIL', 'SMS', 'IN_APP', name='notificationtype'),
               comment=None,
               existing_comment='Delivery method: email, sms, in_app',
               existing_nullable=False)
    op.alter_column('notifications', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Notification title/subject',
               existing_nullable=False)
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Notification message body',
               existing_nullable=False)
    op.alter_column('notifications', 'status',
               existing_type=postgresql.ENUM('PENDING', 'SENT', 'FAILED', name='notificationstatus'),
               comment=None,
               existing_comment='Delivery status: pending, sent, failed',
               existing_nullable=False)
    op.alter_column('notifications', 'error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Error message if delivery failed',
               existing_nullable=True)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether user has read this notification',
               existing_nullable=False)
    op.alter_column('notifications', 'read_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='When user read the notification',
               existing_nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='When notification was created',
               existing_nullable=False)
    op.alter_column('notifications', 'sent_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='When notification was sent',
               existing_nullable=True)
    op.drop_column('portfolios', 'profit_loss_percent')
    op.drop_column('portfolios', 'profit_loss')
    op.alter_column('stock_analyses', 'analysis_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Type: technical, fundamental, sentiment, comprehensive',
               existing_nullable=False)
    op.alter_column('stock_analyses', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='AI confidence in this analysis (0.0-1.0)',
               existing_nullable=False)
    op.alter_column('stock_analyses', 'technical_indicators',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='RSI, MACD, Bollinger Bands, etc.',
               existing_nullable=True)
    op.alter_column('stock_analyses', 'fundamental_metrics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='P/E, debt ratio, revenue growth, etc.',
               existing_nullable=True)
    op.alter_column('stock_analyses', 'sentiment_analysis',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='News sentiment, social media sentiment, etc.',
               existing_nullable=True)
    op.alter_column('stock_analyses', 'summary',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Human-readable summary of the analysis',
               existing_nullable=False)
    op.alter_column('stock_analyses', 'recommendation',
               existing_type=postgresql.ENUM('BUY', 'SELL', 'HOLD', name='signaltype'),
               comment=None,
               existing_comment='Overall recommendation: buy, sell, hold',
               existing_nullable=False)
    op.alter_column('stock_analyses', 'reasoning',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Detailed reasoning for the recommendation',
               existing_nullable=False)
    op.alter_column('stock_analyses', 'risk_level',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Risk level: low, moderate, high',
               existing_nullable=False)
    op.alter_column('stock_analyses', 'agent_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Which agents contributed to this analysis',
               existing_nullable=True)
    op.alter_column('stock_analyses', 'llm_trace_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='LangSmith trace ID for debugging',
               existing_nullable=True)
    op.alter_column('stock_analyses', 'analyzed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='When this analysis was performed',
               existing_nullable=False)
    op.alter_column('stock_analyses', 'valid_until',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='When this analysis becomes stale',
               existing_nullable=True)
    op.drop_column('stock_analyses', 'risk_factors')
    op.alter_column('stocks', 'symbol',
               existing_type=sa.VARCHAR(length=20),
               comment='Stock ticker symbol',
               existing_comment='Stock ticker symbol (e.g., RELIANCE, AAPL)',
               existing_nullable=False)
    op.alter_column('stocks', 'market',
               existing_type=postgresql.ENUM('INDIA_NSE', 'INDIA_BSE', 'US_NYSE', 'US_NASDAQ', name='markettype'),
               comment='Stock market',
               existing_comment='Stock market (NSE, NYSE, etc.)',
               existing_nullable=False)
    op.alter_column('stocks', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Full company name',
               existing_nullable=False)
    op.alter_column('stocks', 'sector',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Business sector (Technology, Finance, etc.)',
               existing_nullable=True)
    op.alter_column('stocks', 'industry',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Industry classification',
               existing_nullable=True)
    op.alter_column('stocks', 'current_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Latest stock price',
               existing_nullable=True)
    op.alter_column('stocks', 'previous_close',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Previous day closing price',
               existing_nullable=True)
    op.alter_column('stocks', 'market_cap',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Market capitalization',
               existing_nullable=True)
    op.alter_column('stocks', 'pe_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Price-to-Earnings ratio',
               existing_nullable=True)
    op.alter_column('stocks', 'stock_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Additional stock metadata (52-week high/low, dividend, etc.)',
               existing_nullable=True)
    op.alter_column('stocks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               comment=None,
               existing_comment='Vector embedding for stock characteristics (for pattern matching)',
               existing_nullable=True)
    op.alter_column('stocks', 'last_data_refresh',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='When market data was last fetched',
               existing_nullable=True)
    op.alter_column('trading_signals', 'analysis_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Related analysis that generated this signal',
               existing_nullable=True)
    op.alter_column('trading_signals', 'signal_type',
               existing_type=postgresql.ENUM('BUY', 'SELL', 'HOLD', name='signaltype'),
               comment=None,
               existing_comment='Signal type: buy, sell, hold',
               existing_nullable=False)
    op.alter_column('trading_signals', 'signal_strength',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Signal strength (0.0-1.0)',
               existing_nullable=False)
    op.alter_column('trading_signals', 'trigger_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Stock price when signal was generated',
               existing_nullable=False)
    op.alter_column('trading_signals', 'target_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Suggested target price',
               existing_nullable=True)
    op.alter_column('trading_signals', 'stop_loss',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Suggested stop-loss price',
               existing_nullable=True)
    op.alter_column('trading_signals', 'reason',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Why this signal was generated',
               existing_nullable=False)
    op.alter_column('trading_signals', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether this signal is still valid',
               existing_nullable=False)
    op.alter_column('trading_signals', 'executed',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether user acted on this signal',
               existing_nullable=False)
    op.alter_column('trading_signals', 'generated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='When signal was generated',
               existing_nullable=False)
    op.alter_column('trading_signals', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='When signal expires',
               existing_nullable=True)
    op.alter_column('users', 'preferred_markets',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='List of preferred markets',
               existing_comment='List of preferred markets (NSE, NYSE, etc.)',
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Account creation timestamp',
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Last update timestamp',
               existing_nullable=False)
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Last login timestamp',
               existing_nullable=True)
    op.alter_column('watchlists', 'alert_on_price_change',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Alert when price changes significantly',
               existing_nullable=False)
    op.alter_column('watchlists', 'alert_threshold_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Price change % that triggers alert',
               existing_nullable=False)
    op.alter_column('watchlists', 'alert_on_ai_signal',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Alert when AI generates buy/sell signal',
               existing_nullable=False)
    op.alter_column('watchlists', 'target_buy_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Alert when price drops to this level',
               existing_nullable=True)
    op.alter_column('watchlists', 'target_sell_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Alert when price rises to this level',
               existing_nullable=True)
    op.alter_column('watchlists', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="User's notes about this stock",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('watchlists', 'notes',
               existing_type=sa.TEXT(),
               comment="User's notes about this stock",
               existing_nullable=True)
    op.alter_column('watchlists', 'target_sell_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Alert when price rises to this level',
               existing_nullable=True)
    op.alter_column('watchlists', 'target_buy_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Alert when price drops to this level',
               existing_nullable=True)
    op.alter_column('watchlists', 'alert_on_ai_signal',
               existing_type=sa.BOOLEAN(),
               comment='Alert when AI generates buy/sell signal',
               existing_nullable=False)
    op.alter_column('watchlists', 'alert_threshold_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Price change % that triggers alert',
               existing_nullable=False)
    op.alter_column('watchlists', 'alert_on_price_change',
               existing_type=sa.BOOLEAN(),
               comment='Alert when price changes significantly',
               existing_nullable=False)
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               comment='Last login timestamp',
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Last update timestamp',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Account creation timestamp',
               existing_nullable=False)
    op.alter_column('users', 'preferred_markets',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='List of preferred markets (NSE, NYSE, etc.)',
               existing_comment='List of preferred markets',
               existing_nullable=True)
    op.alter_column('trading_signals', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='When signal expires',
               existing_nullable=True)
    op.alter_column('trading_signals', 'generated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='When signal was generated',
               existing_nullable=False)
    op.alter_column('trading_signals', 'executed',
               existing_type=sa.BOOLEAN(),
               comment='Whether user acted on this signal',
               existing_nullable=False)
    op.alter_column('trading_signals', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Whether this signal is still valid',
               existing_nullable=False)
    op.alter_column('trading_signals', 'reason',
               existing_type=sa.TEXT(),
               comment='Why this signal was generated',
               existing_nullable=False)
    op.alter_column('trading_signals', 'stop_loss',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Suggested stop-loss price',
               existing_nullable=True)
    op.alter_column('trading_signals', 'target_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Suggested target price',
               existing_nullable=True)
    op.alter_column('trading_signals', 'trigger_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Stock price when signal was generated',
               existing_nullable=False)
    op.alter_column('trading_signals', 'signal_strength',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Signal strength (0.0-1.0)',
               existing_nullable=False)
    op.alter_column('trading_signals', 'signal_type',
               existing_type=postgresql.ENUM('BUY', 'SELL', 'HOLD', name='signaltype'),
               comment='Signal type: buy, sell, hold',
               existing_nullable=False)
    op.alter_column('trading_signals', 'analysis_id',
               existing_type=sa.INTEGER(),
               comment='Related analysis that generated this signal',
               existing_nullable=True)
    op.alter_column('stocks', 'last_data_refresh',
               existing_type=postgresql.TIMESTAMP(),
               comment='When market data was last fetched',
               existing_nullable=True)
    op.alter_column('stocks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               comment='Vector embedding for stock characteristics (for pattern matching)',
               existing_nullable=True)
    op.alter_column('stocks', 'stock_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Additional stock metadata (52-week high/low, dividend, etc.)',
               existing_nullable=True)
    op.alter_column('stocks', 'pe_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Price-to-Earnings ratio',
               existing_nullable=True)
    op.alter_column('stocks', 'market_cap',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Market capitalization',
               existing_nullable=True)
    op.alter_column('stocks', 'previous_close',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Previous day closing price',
               existing_nullable=True)
    op.alter_column('stocks', 'current_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Latest stock price',
               existing_nullable=True)
    op.alter_column('stocks', 'industry',
               existing_type=sa.VARCHAR(length=100),
               comment='Industry classification',
               existing_nullable=True)
    op.alter_column('stocks', 'sector',
               existing_type=sa.VARCHAR(length=100),
               comment='Business sector (Technology, Finance, etc.)',
               existing_nullable=True)
    op.alter_column('stocks', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Full company name',
               existing_nullable=False)
    op.alter_column('stocks', 'market',
               existing_type=postgresql.ENUM('INDIA_NSE', 'INDIA_BSE', 'US_NYSE', 'US_NASDAQ', name='markettype'),
               comment='Stock market (NSE, NYSE, etc.)',
               existing_comment='Stock market',
               existing_nullable=False)
    op.alter_column('stocks', 'symbol',
               existing_type=sa.VARCHAR(length=20),
               comment='Stock ticker symbol (e.g., RELIANCE, AAPL)',
               existing_comment='Stock ticker symbol',
               existing_nullable=False)
    op.add_column('stock_analyses', sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='List of identified risks'))
    op.alter_column('stock_analyses', 'valid_until',
               existing_type=postgresql.TIMESTAMP(),
               comment='When this analysis becomes stale',
               existing_nullable=True)
    op.alter_column('stock_analyses', 'analyzed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='When this analysis was performed',
               existing_nullable=False)
    op.alter_column('stock_analyses', 'llm_trace_id',
               existing_type=sa.VARCHAR(length=255),
               comment='LangSmith trace ID for debugging',
               existing_nullable=True)
    op.alter_column('stock_analyses', 'agent_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Which agents contributed to this analysis',
               existing_nullable=True)
    op.alter_column('stock_analyses', 'risk_level',
               existing_type=sa.VARCHAR(length=20),
               comment='Risk level: low, moderate, high',
               existing_nullable=False)
    op.alter_column('stock_analyses', 'reasoning',
               existing_type=sa.TEXT(),
               comment='Detailed reasoning for the recommendation',
               existing_nullable=False)
    op.alter_column('stock_analyses', 'recommendation',
               existing_type=postgresql.ENUM('BUY', 'SELL', 'HOLD', name='signaltype'),
               comment='Overall recommendation: buy, sell, hold',
               existing_nullable=False)
    op.alter_column('stock_analyses', 'summary',
               existing_type=sa.TEXT(),
               comment='Human-readable summary of the analysis',
               existing_nullable=False)
    op.alter_column('stock_analyses', 'sentiment_analysis',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='News sentiment, social media sentiment, etc.',
               existing_nullable=True)
    op.alter_column('stock_analyses', 'fundamental_metrics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='P/E, debt ratio, revenue growth, etc.',
               existing_nullable=True)
    op.alter_column('stock_analyses', 'technical_indicators',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='RSI, MACD, Bollinger Bands, etc.',
               existing_nullable=True)
    op.alter_column('stock_analyses', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='AI confidence in this analysis (0.0-1.0)',
               existing_nullable=False)
    op.alter_column('stock_analyses', 'analysis_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Type: technical, fundamental, sentiment, comprehensive',
               existing_nullable=False)
    op.add_column('portfolios', sa.Column('profit_loss', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Profit/loss amount'))
    op.add_column('portfolios', sa.Column('profit_loss_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Profit/loss percentage'))
    op.alter_column('notifications', 'sent_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='When notification was sent',
               existing_nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='When notification was created',
               existing_nullable=False)
    op.alter_column('notifications', 'read_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='When user read the notification',
               existing_nullable=True)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               comment='Whether user has read this notification',
               existing_nullable=False)
    op.alter_column('notifications', 'error_message',
               existing_type=sa.TEXT(),
               comment='Error message if delivery failed',
               existing_nullable=True)
    op.alter_column('notifications', 'status',
               existing_type=postgresql.ENUM('PENDING', 'SENT', 'FAILED', name='notificationstatus'),
               comment='Delivery status: pending, sent, failed',
               existing_nullable=False)
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               comment='Notification message body',
               existing_nullable=False)
    op.alter_column('notifications', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment='Notification title/subject',
               existing_nullable=False)
    op.alter_column('notifications', 'notification_type',
               existing_type=postgresql.ENUM('EMAIL', 'SMS', 'IN_APP', name='notificationtype'),
               comment='Delivery method: email, sms, in_app',
               existing_nullable=False)
    op.alter_column('notifications', 'signal_id',
               existing_type=sa.INTEGER(),
               comment='Related trading signal (if applicable)',
               existing_nullable=True)
    # ### end Alembic commands ###
